### ISSUE TITLE
API fails to extract NCode from playerSource

### ISSUE THREAD

**Issue by ErikDombi** [StefH/Blazor.YouTubeDownloader#3]
index of `functionStart` in `body` is -1 in `DecodeUtils#ExtractNCode()`

```md
System.Exception
  HResult=0x80131500
  Message=Can't cut unsupported JSON (need to begin with [ or { ) but got: ;
  Source=YoutubeExplode.Extensions
  StackTrace:
   at YoutubeExplode.Extensions.StringExtensions.CutAfterJSON(String mixedJson) in C:\Users\Erik\source\Blazor.YouTubeDownloader\YoutubeExplode.Extensions\StringExtensions.cs:line 37
   at YoutubeExplode.Extensions.Utils.DecodeUtils.ExtractNCode(String body) in C:\Users\Erik\source\Blazor.YouTubeDownloader\YoutubeExplode.Extensions\Utils\DecodeUtils.cs:line 17
   at YoutubeExplode.Extensions.Utils.UrlDescrambler..ctor(String playerSource) in C:\Users\Erik\source\Blazor.YouTubeDownloader\YoutubeExplode.Extensions\Utils\UrlDescrambler.cs:line 16
   at YoutubeExplode.Extensions.StreamClientExtensions.<GetManifestAndFixStreamUrlsAsync>d__0.MoveNext() in C:\Users\Erik\source\Blazor.YouTubeDownloader\YoutubeExplode.Extensions\StreamClientExtensions.cs:line 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at YoutubeExplode.DemoConsole.Program.<Main>d__0.MoveNext() in C:\Users\Erik\source\Blazor.YouTubeDownloader\YoutubeExplode.DemoConsole\Program.cs:line 20

  This exception was originally thrown at this call stack:
    YoutubeExplode.Extensions.StringExtensions.CutAfterJSON(string) in StringExtensions.cs
    YoutubeExplode.Extensions.Utils.DecodeUtils.ExtractNCode(string) in DecodeUtils.cs
    YoutubeExplode.Extensions.Utils.UrlDescrambler.UrlDescrambler(string) in UrlDescrambler.cs
    YoutubeExplode.Extensions.StreamClientExtensions.GetManifestAndFixStreamUrlsAsync(YoutubeExplode.Videos.Streams.StreamClient, YoutubeExplode.Videos.VideoId, System.Threading.CancellationToken) in StreamClientExtensions.cs
    [External Code]
    YoutubeExplode.DemoConsole.Program.Main(string[]) in Program.cs```

**Comment by StefH** [comment]
@ErikDombi 
Since I've updated YouTubeExplode, it's not needed anymore to use that extensions NuGet.

Can you just use the latest YouTubeExplode?

**Comment by ErikDombi** [comment]
Sorry, I don't totally follow. This is the error I get running [YoutubeExplode.DemoConsole](https://github.com/StefH/Blazor.YouTubeDownloader/tree/main/YoutubeExplode.DemoConsole). I haven't done anything to change the project in any other way.

**Comment by StefH** [comment]
@ErikDombi 

Since some weeks a new version from YoutubeExplode does natively support fast-downloads again. This is version "6.1.0" which I did already use in the Blazor WebAssembly project, but I forgot to upgrade the console app.

This has been fixed now, so if you get the latest version from this project, the YoutubeExplode.DemoConsole should work fine.
